# Primer on linear algebra in Numpy
## Answers
 
**Task 1:**
Go through the tutorial on Linear Algebra in Python here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html.
Paste and run the code from the tutorial in the empty cell below (or create new empty cells below) to get more familiar with the material.


In [17]:
import numpy as np

#Code here - use code samples from link above


**Task 2:**
Create the following matrices:

$X=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 &3 \end{bmatrix},Y=\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 &0\\ 0 & 0 & 1 \end{bmatrix}$ 

Then do the following:
1.	Multiply ```X``` with ```Y``` (```Z1=X.dot(Y)=XY```) and print the result. What do you observe? 
2.	Multiply ```X``` with ```Y``` transpose (```Z2=X.dot(Y.T)```) and print the result. What do you observe? 
3.	What can you tell about matrix ```Y```, given ```Z1``` and ```Z2```? 

In [30]:

#Code here - model answer
X=np.array([[2,3,4],[1,2,3]])
Y=np.array([[0,1,0],[1,0,0],[0,0,1]])

Z1=X.dot(Y)
print(Z1) # this is the dot product of two matrices

Z2=X.dot( Y.T )
print(Z2) # this gives the same output as X.dot(Y)

print("The matrix Y is equal to its transpose, i.e. Y=Y.T")

print(Y)
print(Y.T)



[[3 2 4]
 [2 1 3]]
[[3 2 4]
 [2 1 3]]
The matrix Y is equal to its transpose, i.e. Y=Y.T
[[0 1 0]
 [1 0 0]
 [0 0 1]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]


array([[3, 2, 4],
       [2, 1, 3]])

**Task 3:** 
Create a 2x2 identity matrix ```I``` using the NumPy function ```eye(dim)``` $$ I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $$


In [14]:

#Code here - model answer
I=np.eye(2)
print(I)


[[1. 0.]
 [0. 1.]]


**Task 4:** 
1. Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2. Print the output.
3. What do you observe? 



In [15]:
x=np.array([2,3])
print(x)

#Code here - model answer
print(I.dot(x)) #nothing changes; multiplying by the identity matrix has no effect on vector x


[2 3]
[2. 3.]


**Task 5:**
1.	Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2.	Print the output.
3.	What do you observe? 


In [16]:
X=np.array([[2,3],[4,5]])
print(x)
#Code here- model answer
print(I.dot(X)) #nothing changes; multiplying by the identity matrix has no effect on matrix X

[2 3]
[[2. 3.]
 [4. 5.]]


**Task 6:**
1. Multiply (using dot) matrix $X$ with the inverse matrix, $X^{-1}$ (use the NumPy function ```linalg.inv``` to do so): $XX^{-1}$
2. What do you observe? 




In [5]:
X=np.array([[1,2],[0,1]])

#Code here - model answer
X.dot(np.linalg.inv(X))


array([[1., 0.],
       [0., 1.]])